"""add avatar_url to users

Revision ID: 77ec0b79a97c
Revises: 90e6ec2bd57f
Create Date: 2025-12-26 20:30:47.265918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '77ec0b79a97c'
down_revision: Union[str, None] = '90e6ec2bd57f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        sa.Column('avatar_url', sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(
        'users',
        'avatar_url'
    )
    # ### end Alembic commands ###
